export default {
  lang: 'EN',
  isFahrenheit: false,
  searchValue: '',
  location: '',
  nameLocation: '',
  nameLocationEn: '',
  units: 'metric',
  city: '',
  country: '',
  coords: {
    lat: '',
    lon: '',
    latFormat: '',
    lonFormat: '',
  },
  coordsLat: '',
  coordsLon: '',
  date: '',
  todayWeather: {
    temp: '',
    feelsLike: '',
    feelsLikeText: '',
    summary: '',
    summaryEN: '',
    humidity: '',
    humidityText: '',
    speedWind: '',
    speedWindText: '',
    speedWindText2: '',
    icon: '',
  },
  day1: {
    weekDay: '',
    temp: '',
    icon: '',
  },
  day2: {
    weekDay: '',
    temp: '',
    icon: '',
  },
  day3: {
    weekDay: '',
    temp: '',
    icon: '',
  },
  season: '',
  hours: '',
  searchCityInput: '',
  searchCityButton: '',
  background: '',
  errors: {
    emptyFieldSearch: '',
  },
};
