export default {
  lang: 'EN',
  isFahrenheit: false,
  searchValue: '',
  location: '',
  nameLocation: '',
  units: 'metric',
  city: '',
  country: '',
  coords: {
    lat: '',
    lon: '',
  },
  date: '',
  todayWeather: {
    temp: '',
    feelsLike: '',
    feelsLikeText: '',
    summary: '',
    humidity: '',
    humidityText: '',
    speedWind: '',
    speedWindText: '',
    speedWindText2: '',
    icon: '',
  },
  day1: {
    weekDay: '',
    temp: '',
    summary: '',
    icon: '',
  },
  day2: {
    weekDay: '',
    temp: '',
    summary: '',
    icon: '',
  },
  day3: {
    weekDay: '',
    temp: '',
    summary: '',
    icon: '',
  },
  searchCityInput: '',
  searchCityButton: '',
  coordsLat: '',
  coordsLon: '',
  errors: {
    cityN: '',
    emptyFieldSearch: '',
  },
};
