import state from './state';
import CanvasSize from './components/canvasSize';
import Tool from './components/tool';
import ToolSize from './components/toolSize';
import Color from './components/color';
import Canvas from './components/canvas';
import event from './components/events';
import StaticMethods from './components/staticMethods';
import Frame from './components/frames/frame';
import FrameDrag from './components/frames/frameDrag';

state.mainCanvasObj = new Canvas();
state.toolObj = new Tool();
state.toolSizeObj = new ToolSize();
state.primaryColorObj = new Color('primary');
state.secondaryColorObj = new Color('secondary');
state.canvasSizeObj = new CanvasSize();
state.staticMethodsObj = new StaticMethods();
state.frameObj = new Frame();
state.frameDragObj = new FrameDrag();
event();
